/* tslint:disable */
/* eslint-disable */
/**
 * TaskMate.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Status } from './status';
/**
 * 
 * @export
 * @interface IssueResponse
 */
export interface IssueResponse {
    /**
     * 
     * @type {string}
     * @memberof IssueResponse
     */
    issueId?: string;
    /**
     * 
     * @type {string}
     * @memberof IssueResponse
     */
    creatorId?: string;
    /**
     * 
     * @type {number}
     * @memberof IssueResponse
     */
    priority?: number;
    /**
     * 
     * @type {number}
     * @memberof IssueResponse
     */
    difficulty?: number;
    /**
     * 
     * @type {string}
     * @memberof IssueResponse
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IssueResponse
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IssueResponse
     */
    performerId?: string;
    /**
     * 
     * @type {Date}
     * @memberof IssueResponse
     */
    startDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof IssueResponse
     */
    endDate?: Date;
    /**
     * 
     * @type {Status}
     * @memberof IssueResponse
     */
    status?: Status;
    /**
     * 
     * @type {string}
     * @memberof IssueResponse
     */
    projectId?: string;
}
