/* tslint:disable */
/* eslint-disable */
/**
 * TaskMate.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Issue } from './issue';
import { User } from './user';
/**
 * 
 * @export
 * @interface IssueLog
 */
export interface IssueLog {
    /**
     * 
     * @type {string}
     * @memberof IssueLog
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof IssueLog
     */
    issueId?: string;
    /**
     * 
     * @type {Issue}
     * @memberof IssueLog
     */
    issue?: Issue;
    /**
     * 
     * @type {string}
     * @memberof IssueLog
     */
    userId?: string;
    /**
     * 
     * @type {User}
     * @memberof IssueLog
     */
    user?: User;
    /**
     * 
     * @type {string}
     * @memberof IssueLog
     */
    propertyName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IssueLog
     */
    oldValue?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IssueLog
     */
    newValue?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof IssueLog
     */
    changeDateTime?: Date;
}
