/* tslint:disable */
/* eslint-disable */
/**
 * TaskMate.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IssueResponse } from './issue-response';
/**
 * 
 * @export
 * @interface IssuesResponse
 */
export interface IssuesResponse {
    /**
     * 
     * @type {Array<IssueResponse>}
     * @memberof IssuesResponse
     */
    issues?: Array<IssueResponse> | null;
}
