/* tslint:disable */
/* eslint-disable */
/**
 * TaskMate.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Status } from './status';
/**
 * 
 * @export
 * @interface IssueRequest
 */
export interface IssueRequest {
    /**
     * 
     * @type {string}
     * @memberof IssueRequest
     */
    creatorId: string;
    /**
     * 
     * @type {number}
     * @memberof IssueRequest
     */
    priority: number;
    /**
     * 
     * @type {number}
     * @memberof IssueRequest
     */
    difficulty: number;
    /**
     * 
     * @type {string}
     * @memberof IssueRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof IssueRequest
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof IssueRequest
     */
    performerId: string;
    /**
     * 
     * @type {Date}
     * @memberof IssueRequest
     */
    startDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof IssueRequest
     */
    endDate: Date;
    /**
     * 
     * @type {Status}
     * @memberof IssueRequest
     */
    status: Status;
    /**
     * 
     * @type {string}
     * @memberof IssueRequest
     */
    projectId: string;
}
