/* tslint:disable */
/* eslint-disable */
/**
 * TaskMate.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Project } from './project';
import { Status } from './status';
import { User } from './user';
/**
 * 
 * @export
 * @interface Issue
 */
export interface Issue {
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    creatorId?: string;
    /**
     * 
     * @type {User}
     * @memberof Issue
     */
    creator?: User;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    performerId?: string;
    /**
     * 
     * @type {User}
     * @memberof Issue
     */
    performer?: User;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    projectId?: string;
    /**
     * 
     * @type {Project}
     * @memberof Issue
     */
    project?: Project;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Issue
     */
    priority?: number;
    /**
     * 
     * @type {number}
     * @memberof Issue
     */
    difficulty?: number;
    /**
     * 
     * @type {Date}
     * @memberof Issue
     */
    startDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Issue
     */
    endDate?: Date;
    /**
     * 
     * @type {Status}
     * @memberof Issue
     */
    status?: Status;
}
