/* tslint:disable */
/* eslint-disable */
/**
 * TaskMate.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProjectUserResponse } from './project-user-response';
/**
 * 
 * @export
 * @interface ProjectUsersResponse
 */
export interface ProjectUsersResponse {
    /**
     * 
     * @type {Array<ProjectUserResponse>}
     * @memberof ProjectUsersResponse
     */
    projectUsers?: Array<ProjectUserResponse> | null;
}
