/* tslint:disable */
/* eslint-disable */
/**
 * TaskMate.WebApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ProjectUserResponse
 */
export interface ProjectUserResponse {
    /**
     * 
     * @type {string}
     * @memberof ProjectUserResponse
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectUserResponse
     */
    projectId?: string;
}
